// Generated by CoffeeScript 1.6.2
var clc, util;

util = require('util');

clc = require('cli-color');

process.title = '4press';

module.exports = {
  help: function(args) {
    return require('./usage.js').help();
  },
  deploy: function(args) {
    return require('./deploy')(args);
  },
  server: function(args) {
    return require('./server.js');
  },
  build: function(args) {
    return require('./build.js')(args);
  },
  post: function(args) {
    return require('./post.js')(args);
  },
  page: function(args) {
    return require('./page.js')(args);
  },
  "new": function(args) {
    return require('./new')(args);
  }
};
