// Generated by CoffeeScript 1.3.3
var newFile, parseArg, usage;

newFile = require('./post');

usage = require('./usage');

parseArg = require('./arg').parse;

module.exports = function(args) {
  var arg, filename;
  arg = parseArg(args);
  if ((args.length === 0) || (arg.req.length === 0)) {
    usage.puts('pages');
    return;
  }
  filename = file.titleToPath(arg.req);
  return newFile(arg, filename, './data/pages/', 'page');
};
